version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - 27017:27017
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: password
    volumes:
      - my-mongo-data:/data/db
    networks:
      - mongo-network
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/?authSource=admin
    networks:
      - mongo-network

volumes:
  my-mongo-data:
    driver: local

networks:
  mongo-network:
